stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "build başarılı"
    - npm install
    - npm run build

test_job:
  stage: test
  script:
    - echo "test başarılı"
    - npm test
