services:
  mongo:
    image: mongo:6
    container_name: mypictures-mongo
    restart: always
    ports:
      - "27017:27017"             
    volumes:
      - ./mongo_data:/data/db     # Veriler host klasörüne kaydedilecek

  backend:
    build: ./backend
    container_name: mypictures-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env            
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mypictures-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
